# This file is a derivation from https://github.com/simplesteph/kafka-stack-docker-compose
# Which the Apache License 2.0 which can be found here
# https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/LICENSE
#
version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-multiple/zoo1/data:/data
      - ./zk-single-kafka-multiple/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    container_name: kafka_broker-1
    ports:
      - "9092:9092"
      - "9093:9093"

    volumes:
      - ./cert/jks:/etc/kafka/secrets
      - ./config:/etc/kafka/
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,SSL://kafka1:9093
      KAFKA_NUM_PARTITIONS: 6

      # For testing small segments 16MB and retention of 128MB
      KAFKA_LOG_SEGMENT_BYTES: 16777216
      KAFKA_LOG_RETENTION_BYTES: 134217728
      KAFKA_SSL_KEYSTORE_FILENAME: "kafka1.keystore.jks"
      KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.server.truststore.jks"

      KAFKA_SSL_KEY_CREDENTIALS: "kafka.key"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "kafka.key"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "kafka.key"
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_METRIC_REPORTERS:
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,state.change.logger=WARN"
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.2"
      KAFKA_SUPER_USERS: User:CN=kafka1,OU=kafka,O=kafka,L=kafka,ST=WI,C=US
      #KAFKA_ZOOKEEPER_SET_ACL: "true"

      # KAFKA_SSL_TRUSTSTORE_TYPE: "pkcs12"
    depends_on:
      - zoo1
